# (Des)carga de base de datos

## Instalación y carga de la librería del repositorio UCI ML

Instalar la librería del repositorio utilizando pip.

In [1]:
pip install ucimlrepo

Collecting ucimlrepo
  Using cached ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /Users/davidmoreno/miniconda3/envs/dmemcdm1/lib/python3.11/site-packages (from ucimlrepo) (2.3.3)
Collecting certifi>=2020.12.5 (from ucimlrepo)
  Downloading certifi-2025.10.5-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy>=1.23.2 in /Users/davidmoreno/miniconda3/envs/dmemcdm1/lib/python3.11/site-packages (from pandas>=1.0.0->ucimlrepo) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/davidmoreno/miniconda3/envs/dmemcdm1/lib/python3.11/site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/davidmoreno/miniconda3/envs/dmemcdm1/lib/python3.11/site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/davidmoreno/miniconda3/envs/dmemcdm1/lib/python3.11/site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/davidmoreno/miniconda3/envs/dmemcdm1/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Using cached ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)
Installing collected packages: certifi, ucimlrepo
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [ucimlrepo]
Successfully installed certifi-2025.10.5 ucimlrepo-0.0.7
Note: you may need to restart the kernel to use updated packages.

Verificar que la librería del repositorio se encuentra correctamente instalada.

In [4]:
pip list | grep uci

ucimlrepo               0.0.7
Note: you may need to restart the kernel to use updated packages.

Cargar la librería en la sesión actual de python.

In [5]:
from ucimlrepo import fetch_ucirepo

## Carga de la base de datos de cirrosis

Según la documentación del repositorio, nuestra base de datos de interés (cirrosis) se encuentra indexada con el id 878.

In [6]:
cirrhosis_patient_survival_prediction = fetch_ucirepo(id=878)

Ver cómo viene la información

In [7]:
cirrhosis_patient_survival_prediction

{'data': {'ids':       ID
  0      1
  1      2
  2      3
  3      4
  4      5
  ..   ...
  413  414
  414  415
  415  416
  416  417
  417  418

  [418 rows x 1 columns],
  'features':                 Drug    Age Sex Ascites Hepatomegaly Spiders Edema  Bilirubin  \
  0    D-penicillamine  21464   F       Y            Y       Y     Y       14.5
  1    D-penicillamine  20617   F       N            Y       Y     N        1.1
  2    D-penicillamine  25594   M       N            N       N     S        1.4
  3    D-penicillamine  19994   F       N            Y       Y     S        1.8
  4            Placebo  13918   F       N            Y       Y     N        3.4
  ..               ...    ...  ..     ...          ...     ...   ...        ...
  413              NaN  24472   F     NaN          NaN     NaN     N        1.2
  414              NaN  14245   F     NaN          NaN     NaN     N        0.9
  415              NaN  20819   F     NaN          NaN     NaN     N        1.6
  416              NaN  21185   F     NaN          NaN     NaN     N        0.8
  417              NaN  19358   F     NaN          NaN     NaN     N        0.7

      Cholesterol  Albumin Copper  Alk_Phos    SGOT Tryglicerides Platelets  \
  0           261     2.60    156    1718.0  137.95           172       190
  1           302     4.14     54    7394.8  113.52            88       221
  2           176     3.48    210     516.0   96.10            55       151
  3           244     2.54     64    6121.8   60.63            92       183
  4           279     3.53    143     671.0  113.15            72       136
  ..          ...      ...    ...       ...     ...           ...       ...
  413         NaN     2.96    NaN       NaN     NaN           NaN       174
  414         NaN     3.83    NaN       NaN     NaN           NaN       180
  415         NaN     3.42    NaN       NaN     NaN           NaN       143
  416         NaN     3.75    NaN       NaN     NaN           NaN       269
  417         NaN     3.29    NaN       NaN     NaN           NaN       350

       Prothrombin  Stage
  0           12.2    4.0
  1           10.6    3.0
  2           12.0    4.0
  3           10.3    4.0
  4           10.9    3.0
  ..           ...    ...
  413         10.9    3.0
  414         11.2    4.0
  415          9.9    3.0
  416         10.4    3.0
  417         10.6    4.0

  [418 rows x 17 columns],
  'targets':     Status
  0        D
  1        C
  2        D
  3        D
  4       CL
  ..     ...
  413      D
  414      C
  415      C
  416      C
  417      C

  [418 rows x 1 columns],
  'original':       ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
  0      1     400      D  D-penicillamine  21464   F       Y            Y
  1      2    4500      C  D-penicillamine  20617   F       N            Y
  2      3    1012      D  D-penicillamine  25594   M       N            N
  3      4    1925      D  D-penicillamine  19994   F       N            Y
  4      5    1504     CL          Placebo  13918   F       N            Y
  ..   ...     ...    ...              ...    ...  ..     ...          ...
  413  414     681      D              NaN  24472   F     NaN          NaN
  414  415    1103      C              NaN  14245   F     NaN          NaN
  415  416    1055      C              NaN  20819   F     NaN          NaN
  416  417     691      C              NaN  21185   F     NaN          NaN
  417  418     976      C              NaN  19358   F     NaN          NaN

      Spiders Edema  Bilirubin Cholesterol  Albumin Copper  Alk_Phos    SGOT  \
  0         Y     Y       14.5         261     2.60    156    1718.0  137.95
  1         Y     N        1.1         302     4.14     54    7394.8  113.52
  2         N     S        1.4         176     3.48    210     516.0   96.10
  3         Y     S        1.8         244     2.54     64    6121.8   60.63
  4         Y     N        3.4         279     3.53    143     671.0  113.15
  ..      ...   ...        ...         ...      ...    ...       ...     ...
  413     NaN     N        1.2         NaN     2.96    NaN       NaN     NaN
  414     NaN     N        0.9         NaN     3.83    NaN       NaN     NaN
  415     NaN     N        1.6         NaN     3.42    NaN       NaN     NaN
  416     NaN     N        0.8         NaN     3.75    NaN       NaN     NaN
  417     NaN     N        0.7         NaN     3.29    NaN       NaN     NaN

      Tryglicerides Platelets  Prothrombin  Stage
  0             172       190         12.2    4.0
  1              88       221         10.6    3.0
  2              55       151         12.0    4.0
  3              92       183         10.3    4.0
  4              72       136         10.9    3.0
  ..            ...       ...          ...    ...
  413           NaN       174         10.9    3.0
  414           NaN       180         11.2    4.0
  415           NaN       143          9.9    3.0
  416           NaN       269         10.4    3.0
  417           NaN       350         10.6    4.0

  [418 rows x 20 columns],
  'headers': Index(['ID', 'N_Days', 'Status', 'Drug', 'Age', 'Sex', 'Ascites',
         'Hepatomegaly', 'Spiders', 'Edema', 'Bilirubin', 'Cholesterol',
         'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets',
         'Prothrombin', 'Stage'],
        dtype='object')},
 'metadata': {'uci_id': 878,
  'name': 'Cirrhosis Patient Survival Prediction',
  'repository_url': 'https://archive.ics.uci.edu/dataset/878/cirrhosis+patient+survival+prediction+dataset-1',
  'data_url': 'https://archive.ics.uci.edu/static/public/878/data.csv',
  'abstract': 'Utilize 17 clinical features for predicting survival state of patients with liver cirrhosis. The survival states include 0 = D (death), 1 = C (censored), 2 = CL (censored due to liver transplantation).',
  'area': 'Health and Medicine',
  'tasks': ['Classification'],
  'characteristics': ['Tabular'],
  'num_instances': 418,
  'num_features': 17,
  'feature_types': ['Real', 'Categorical'],
  'demographics': ['Age', 'Sex'],
  'target_col': ['Status'],
  'index_col': ['ID'],
  'has_missing_values': 'yes',
  'missing_values_symbol': 'NaN',
  'year_of_dataset_creation': 1989,
  'last_updated': 'Fri Nov 03 2023',
  'dataset_doi': '10.24432/C5R02G',
  'creators': ['E. Dickson',
   'P. Grambsch',
   'T. Fleming',
   'L. Fisher',
   'A. Langworthy'],
  'intro_paper': {'ID': 296,
   'type': 'NATIVE',
   'title': 'Prognosis in primary biliary cirrhosis: Model for decision making',
   'authors': 'E. Dickson, P. Grambsch, T. Fleming, L. Fisher, A. Langworthy',
   'venue': 'Hepatology',
   'year': 1989,
   'journal': None,
   'DOI': None,
   'URL': 'https://www.semanticscholar.org/paper/db1487216b8a4b26f5e5078ea9109ac9d8355b65',
   'sha': None,
   'corpus': None,
   'arxiv': None,
   'mag': None,
   'acl': None,
   'pmid': None,
   'pmcid': None},
  'additional_info': {'summary': "During 1974 to 1984, 424 PBC patients referred to the Mayo Clinic qualified for the randomized placebo-controlled trial testing the drug D-penicillamine. Of these, the initial 312 patients took part in the trial and have mostly comprehensive data. The remaining 112 patients didn't join the clinical trial but agreed to record basic metrics and undergo survival tracking. Six of these patients were soon untraceable after their diagnosis, leaving data for 106 of these individuals in addition to the 312 who were part of the randomized trial.",
   'purpose': 'Cirrhosis results from prolonged liver damage, leading to extensive scarring, often due to conditions like hepatitis or chronic alcohol consumption. The data provided is sourced from a Mayo Clinic study on primary biliary cirrhosis (PBC) of the liver carried out from 1974 to 1984.',
   'funded_by': 'Mayo Clinic',
   'instances_represent': 'People',
   'recommended_data_splits': None,
   'sensitive_data': 'Gender, Age',
   'preprocessing_description': '1. Drop all the rows where miss value (NA) were present in the Drug column\n2. Impute missing values with mean results\n3. One-hot encoding for all category attributes',
   'variable_info': '1. ID: unique identifier\n2. N_Days: number of days between registration and the earlier of death, transplantation, or study analysis time in July 1986\n3. Status: status of the patient C (censored), CL (censored due to liver tx), or D (death)\n4. Drug: type of drug D-penicillamine or placebo\n5. Age: age in [days]\n6. Sex: M (male) or F (female)\n7. Ascites: presence of ascites N (No) or Y (Yes)\n8. Hepatomegaly: presence of hepatomegaly N (No) or Y (Yes)\n9. Spiders: presence of spiders N (No) or Y (Yes)\n10. Edema: presence of edema N (no edema and no diuretic therapy for edema), S (edema present without diuretics, or edema resolved by diuretics), or Y (edema despite diuretic therapy)\n11. Bilirubin: serum bilirubin in [mg/dl]\n12. Cholesterol: serum cholesterol in [mg/dl]\n13. Albumin: albumin in [gm/dl]\n14. Copper: urine copper in [ug/day]\n15. Alk_Phos: alkaline phosphatase in [U/liter]\n16. SGOT: SGOT in [U/ml]\n17. Triglycerides: triglicerides in [mg/dl]\n18. Platelets: platelets per cubic [ml/1000]\n19. Prothrombin: prothrombin time in seconds [s]\n20. Stage: histologic stage of disease (1, 2, 3, or 4)\n',
   'citation': 'Fleming, Thomas R., and David P. Harrington. Counting processes and survival analysis. Vol. 625. John Wiley & Sons, 2013.'}},
 'variables':              name     role         type demographic  \
 0              ID       ID      Integer        None
 1          N_Days    Other      Integer        None
 2          Status   Target  Categorical        None
 3            Drug  Feature  Categorical        None
 4             Age  Feature      Integer         Age
 5             Sex  Feature  Categorical         Sex
 6         Ascites  Feature  Categorical        None
 7    Hepatomegaly  Feature  Categorical        None
 8         Spiders  Feature  Categorical        None
 9           Edema  Feature  Categorical        None
 10      Bilirubin  Feature   Continuous        None
 11    Cholesterol  Feature      Integer        None
 12        Albumin  Feature   Continuous        None
 13         Copper  Feature      Integer        None
 14       Alk_Phos  Feature   Continuous        None
 15           SGOT  Feature   Continuous        None
 16  Tryglicerides  Feature      Integer        None
 17      Platelets  Feature      Integer        None
 18    Prothrombin  Feature   Continuous        None
 19          Stage  Feature  Categorical        None

                                           description    units missing_values
 0                                   unique identifier     None             no
 1   number of days between registration and the ea...     None             no
 2   status of the patient C (censored), CL (censor...     None             no
 3             type of drug D-penicillamine or placebo     None            yes
 4                                                 age     days             no
 5                              M (male) or F (female)     None             no
 6               presence of ascites N (No) or Y (Yes)     None            yes
 7          presence of hepatomegaly N (No) or Y (Yes)     None            yes
 8               presence of spiders N (No) or Y (Yes)     None            yes
 9   presence of edema N (no edema and no diuretic ...     None             no
 10                                    serum bilirubin    mg/dl             no
 11                                  serum cholesterol    mg/dl            yes
 12                                            albumin    gm/dl             no
 13                                       urine copper   ug/day            yes
 14                               alkaline phosphatase  U/liter            yes
 15                                               SGOT     U/ml            yes
 16                                      tryglicerides     None            yes
 17                                platelets per cubic  ml/1000            yes
 18                                   prothrombin time        s            yes
 19        histologic stage of disease (1, 2, 3, or 4)     None            yes  }

Estructurar la información en un data frame

In [ ]:
X = cirrhosis_patient_survival_prediction.data.features
y = cirrhosis_patient_survival_prediction.data.targets
cirrosis = pd.concat([X,y], axis=1)

Ver las primeras observaciones

In [35]:
cirrosis.head(10)

,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2,4.0,D
1,D-penicillamine,20617,F,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6,3.0,C
2,D-penicillamine,25594,M,N,N,N,S,1.4,176,3.48,210,516.0,96.10,55,151,12.0,4.0,D
3,D-penicillamine,19994,F,N,Y,Y,S,1.8,244,2.54,64,6121.8,60.63,92,183,10.3,4.0,D
4,Placebo,13918,F,N,Y,Y,N,3.4,279,3.53,143,671.0,113.15,72,136,10.9,3.0,CL
5,Placebo,24201,F,N,Y,N,N,0.8,248,3.98,50,944.0,93.00,63,NaNN,11.0,3.0,D
6,Placebo,20284,F,N,Y,N,N,1.0,322,4.09,52,824.0,60.45,213,204,9.7,3.0,C
7,Placebo,19379,F,N,N,N,N,0.3,280,4.00,52,4651.2,28.38,189,373,11.0,3.0,D
8,D-penicillamine,15526,F,N,N,Y,N,3.2,562,3.08,79,2276.0,144.15,88,251,11.0,2.0,D
9,Placebo,25772,F,Y,N,Y,Y,12.6,200,2.74,140,918.0,147.25,143,302,11.5,4.0,D

## En caso que fracasemos con la librería uci

Cargar librerías auxiliares

In [9]:
# Importar clase Path para utilizar rutas en directorios
from pathlib import Path
# Importar pandas para cargar base como dataframe
import pandas as pd

Ruta de trabajo actual para movernos entre directorios y poder leer la base correctamente.

In [16]:
BASE_DIR = Path().resolve().parent

Ver cual es el directorio al que apunta BASE_DIR

In [17]:
BASE_DIR

PosixPath('/Users/davidmoreno/Desktop/Diplomado 2025/DMEMCDM1')

Ruta de del directorio donde se encuentra el archivo de cirrosis

In [18]:
DATA_DIR = BASE_DIR / 'data' / 'cirrosis'
DATA_DIR

PosixPath('/Users/davidmoreno/Desktop/Diplomado 2025/DMEMCDM1/data/cirrosis')

Leer el archivo csv que se encuentra en el directorio de cirrosis utilizando pandas para estructurarlo en un data frame.

In [36]:
cirrosis2 = pd.read_csv(DATA_DIR / 'cirrhosis.csv')

Ver las primeros renglones del data frame.

In [37]:
cirrosis2.head(10)

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261.0,2.60,156.0,1718.0,137.95,172.0,190.0,12.2,4.0
1,2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302.0,4.14,54.0,7394.8,113.52,88.0,221.0,10.6,3.0
2,3,1012,D,D-penicillamine,25594,M,N,N,N,S,1.4,176.0,3.48,210.0,516.0,96.10,55.0,151.0,12.0,4.0
3,4,1925,D,D-penicillamine,19994,F,N,Y,Y,S,1.8,244.0,2.54,64.0,6121.8,60.63,92.0,183.0,10.3,4.0
4,5,1504,CL,Placebo,13918,F,N,Y,Y,N,3.4,279.0,3.53,143.0,671.0,113.15,72.0,136.0,10.9,3.0
5,6,2503,D,Placebo,24201,F,N,Y,N,N,0.8,248.0,3.98,50.0,944.0,93.00,63.0,NaN,11.0,3.0
6,7,1832,C,Placebo,20284,F,N,Y,N,N,1.0,322.0,4.09,52.0,824.0,60.45,213.0,204.0,9.7,3.0
7,8,2466,D,Placebo,19379,F,N,N,N,N,0.3,280.0,4.00,52.0,4651.2,28.38,189.0,373.0,11.0,3.0
8,9,2400,D,D-penicillamine,15526,F,N,N,Y,N,3.2,562.0,3.08,79.0,2276.0,144.15,88.0,251.0,11.0,2.0
9,10,51,D,Placebo,25772,F,Y,N,Y,Y,12.6,200.0,2.74,140.0,918.0,147.25,143.0,302.0,11.5,4.0

## Sanity check

Verificar que tienen la misma dimensión

In [39]:
cirrosis.shape

(418, 18)

In [40]:
cirrosis2.shape

(418, 20)

Observamos que en cirrosis2 existen un par de columnas que no se encontraban en cirrosis:

In [44]:
set(cirrosis2.columns).symmetric_difference(set(cirrosis.columns))

{'ID', 'N_Days'}

La columna 'ID' sirve de identificador por lo cual no representa ninguna diferencia significativa que pudiera afectar el análisis de nuestros datos. ¿Pero que pasa con 'N_Days'?

**Revisando la documentación** encontramos que dicha variable representaba el tiempo transcurrido desde que se registraban al estudio a que pasaba uno de los siguientes escenarios:
1. Muerte (D)
2. Trasplante (CL)
3. Fin del estudio (C)

Cómo nosotros no estamos haciendo el análisis de supervivencia y tomamos los datos con fines meramente de estudio, vamos a considerar N_Days también como variable explicativa.

## "Arreglo" de las bases

Primero voy a buscar como agregar la columna N_Days a mi base cirrosis. Explorando el objeto cirrhosis_patient_survival_prediction vemos que en data había un original que es idéntica a la tabla generada con cirrosis2.

In [48]:
cirrosis = cirrhosis_patient_survival_prediction.data.original
cirrosis.head(10)

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2,4.0
1,2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6,3.0
2,3,1012,D,D-penicillamine,25594,M,N,N,N,S,1.4,176,3.48,210,516.0,96.10,55,151,12.0,4.0
3,4,1925,D,D-penicillamine,19994,F,N,Y,Y,S,1.8,244,2.54,64,6121.8,60.63,92,183,10.3,4.0
4,5,1504,CL,Placebo,13918,F,N,Y,Y,N,3.4,279,3.53,143,671.0,113.15,72,136,10.9,3.0
5,6,2503,D,Placebo,24201,F,N,Y,N,N,0.8,248,3.98,50,944.0,93.00,63,NaNN,11.0,3.0
6,7,1832,C,Placebo,20284,F,N,Y,N,N,1.0,322,4.09,52,824.0,60.45,213,204,9.7,3.0
7,8,2466,D,Placebo,19379,F,N,N,N,N,0.3,280,4.00,52,4651.2,28.38,189,373,11.0,3.0
8,9,2400,D,D-penicillamine,15526,F,N,N,Y,N,3.2,562,3.08,79,2276.0,144.15,88,251,11.0,2.0
9,10,51,D,Placebo,25772,F,Y,N,Y,Y,12.6,200,2.74,140,918.0,147.25,143,302,11.5,4.0

In [50]:
all(cirrosis == cirrosis2)

True

De esta manera, podemos quedarnos solo con cirrosis, "descartando" la columna 'ID', y eliminar el objeto cirrosis2.

OJO: Dependiendo de la base que pudieron descargar, a esa le "descartan" la columna 'ID' y la otra no existía entonces no la borran.

In [71]:
cirrosis.set_index('ID', inplace=True)
cirrosis.head(2)

,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
ID,,,,,,,,,,,,,,,,,,,
1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2,4.0
2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6,3.0

In [59]:
del cirrosis2

In [61]:
cirrhosis_patient_survival_prediction.data.original.shape

(418, 19)